export const PAGE_EXAMPLES = [
  {
    id: 'list-standard',
    group: 'list',
    title: 'Khách hàng doanh nghiệp',
    icon: 'business',
    description: 'Tra cứu, quản lý thông tin và theo dõi khách hàng.',
  },
  {
    id: 'list-advanced-filter',
    group: 'list',
    title: 'Quản lý đơn hàng',
    icon: 'shopping_cart',
    description: 'Theo dõi đơn hàng theo trạng thái và khu vực giao nhận.',
  },
  {
    id: 'list-grouped-tree',
    group: 'list',
    title: 'Danh mục sản phẩm',
    icon: 'account_tree',
    description: 'Quản lý nhóm sản phẩm và các mặt hàng trực thuộc.',
  },
  {
    id: 'list-master-detail',
    group: 'list',
    title: 'Yêu cầu hỗ trợ',
    icon: 'support_agent',
    description: 'Tiếp nhận và xử lý yêu cầu trong cùng không gian làm việc.',
  },
  {
    id: 'detail-overview',
    group: 'detail',
    title: 'Hồ sơ khách hàng',
    icon: 'badge',
    description: 'Thông tin khách hàng, liên hệ và giá trị hợp tác.',
  },
  {
    id: 'detail-tabbed',
    group: 'detail',
    title: 'Hợp đồng cung ứng',
    icon: 'contract',
    description: 'Thông tin hợp đồng và danh sách hạng mục liên quan.',
  },
  {
    id: 'detail-related-records',
    group: 'detail',
    title: 'Chi tiết đơn hàng',
    icon: 'receipt_long',
    description: 'Thông tin giao nhận và các dòng hàng trong đơn.',
  },
  {
    id: 'form-simple',
    group: 'detail',
    title: 'Danh mục hàng hóa',
    icon: 'category',
    description: 'Xem, tạo mới và cập nhật danh mục hàng hóa.',
  },
  {
    id: 'form-sections',
    group: 'detail',
    title: 'Hồ sơ đối tác',
    icon: 'handshake',
    description: 'Thông tin chung và đầu mối phối hợp của đối tác.',
  },
  {
    id: 'form-line-items',
    group: 'detail',
    title: 'Đơn hàng có dòng hàng',
    icon: 'list_alt',
    description: 'Lập đơn và tính giá trị từ số lượng, đơn giá từng mặt hàng.',
  },
  {
    id: 'drawer-compact',
    group: 'detail',
    title: 'Danh mục · Drawer',
    icon: 'view_sidebar',
    description: 'Xử lý danh mục trong bảng bên cạnh danh sách.',
  },
  {
    id: 'drawer-sections',
    group: 'detail',
    title: 'Liên hệ · Drawer',
    icon: 'contact_page',
    description: 'Quản lý thông tin liên hệ trong bảng nhiều nhóm thông tin.',
  },
] as const;
