export const PAGE_EXAMPLES = [
  {
    id: 'list-score-filter',
    path: 'order/summary',
    group: 'list',
    title: 'Đơn hàng · Thống kê tương tác',
    icon: 'dashboard',
    description: 'Chọn thẻ để lọc trạng thái; thống kê từ API riêng, cập nhật theo tên đơn hàng và khu vực.',
  },
  {
    id: 'list-standard',
    path: 'company',
    group: 'list',
    title: 'Khách hàng doanh nghiệp',
    icon: 'business',
    description: 'Tìm nhanh và lọc trạng thái; mở chi tiết, tạo mới và cập nhật từ danh sách.',
  },
  {
    id: 'list-advanced-filter',
    path: 'order',
    group: 'list',
    title: 'Quản lý đơn hàng',
    icon: 'shopping_cart',
    description: 'Thẻ thống kê kết hợp bộ lọc trạng thái và khu vực, hỗ trợ chọn nhiều đơn hàng.',
  },
  {
    id: 'list-grouped-tree',
    path: 'product',
    group: 'list',
    title: 'Danh mục sản phẩm',
    icon: 'account_tree',
    description: 'Bảng phân cấp nhóm sản phẩm và mặt hàng, có bộ lọc bên ngoài.',
  },
  {
    id: 'list-master-detail',
    path: 'ticket',
    group: 'list',
    title: 'Yêu cầu hỗ trợ',
    icon: 'support_agent',
    description: 'Danh sách và chi tiết gọn trong Section; chỉnh sửa bằng Side Drawer.',
  },
  {
    id: 'detail-overview',
    path: 'customer',
    group: 'detail',
    title: 'Hồ sơ khách hàng',
    icon: 'badge',
    description: 'Chi tiết ít thông tin trên một trang, mở từ mã khách hàng trong danh sách.',
  },
  {
    id: 'detail-tabbed',
    path: 'contract',
    group: 'detail',
    title: 'Hợp đồng cung ứng',
    icon: 'description',
    description: 'Chi tiết hợp đồng chia tab thông tin chung và hạng mục liên quan.',
  },
  {
    id: 'detail-related-records',
    path: 'order/related-record',
    group: 'detail',
    title: 'Đơn hàng · Hạng mục',
    icon: 'receipt_long',
    description: 'Chi tiết đơn hàng kết hợp thông tin giao nhận và bảng hạng mục.',
  },
  {
    id: 'form-simple',
    path: 'category',
    group: 'detail',
    title: 'Danh mục hàng hóa',
    icon: 'category',
    description: 'Biểu mẫu ít trường, phù hợp với danh mục đơn giản.',
  },
  {
    id: 'form-sections',
    path: 'partner',
    group: 'detail',
    title: 'Hồ sơ đối tác',
    icon: 'handshake',
    description: 'Biểu mẫu chia nhiều Section cho thông tin chung và đầu mối liên hệ.',
  },
  {
    id: 'form-line-items',
    path: 'order/line-item',
    group: 'detail',
    title: 'Đơn hàng có dòng hàng',
    icon: 'list_alt',
    description: 'Biểu mẫu có dòng hàng, tính giá trị từ số lượng và đơn giá.',
  },
  {
    id: 'drawer-compact',
    path: 'category/side-drawer',
    group: 'detail',
    title: 'Danh mục · Side Drawer',
    icon: 'view_sidebar',
    description: 'Xem và chỉnh sửa danh mục bằng Side Drawer gọn ngay tại danh sách.',
  },
  {
    id: 'drawer-sections',
    path: 'contact',
    group: 'detail',
    title: 'Liên hệ · Side Drawer',
    icon: 'contact_page',
    description: 'Side Drawer chia nhóm thông tin, phù hợp với hồ sơ liên hệ.',
  },
] as const;
