/** Navigation metadata only. Article content and demos are lazy-loaded by routes. */
export const INSTRUCTIONS = [
  {
    id: 'overview',
    group: 'Bắt đầu',
    title: 'Tổng quan Portal & Core',
    path: 'getting-started/overview',
    icon: 'explore',
    description: 'Chọn đúng nơi để học API, thử giao diện và tham khảo page nghiệp vụ.',
    order: 1,
  },
  {
    id: 'setup',
    group: 'Bắt đầu',
    title: 'Cài đặt và chạy dự án',
    path: 'getting-started/setup',
    icon: 'terminal',
    description: 'Từ checkout sạch đến Portal và Storybook đang chạy.',
    order: 2,
  },
  {
    id: 'architecture',
    group: 'Kiến trúc & tích hợp',
    title: 'Module & Feature',
    path: 'architecture',
    icon: 'account_tree',
    description: 'Đóng gói nghiệp vụ độc lập, tổ chức theo modules → features.',
    order: 3,
  },
  {
    id: 'routing',
    group: 'Kiến trúc & tích hợp',
    title: 'Routing & Public API',
    path: 'architecture/routing',
    icon: 'route',
    description: 'URL rõ ràng cho từng hành động, lazy-load qua public entry.',
    order: 4,
  },
  {
    id: 'configuration',
    group: 'Kiến trúc & tích hợp',
    title: 'Configuration & API',
    path: 'architecture/configuration',
    icon: 'settings_ethernet',
    description: 'Truyền cấu hình từ Portal; module sở hữu service và xử lý lỗi.',
    order: 5,
  },
  {
    id: 'integration',
    group: 'Kiến trúc & tích hợp',
    title: 'Tích hợp module vào Portal',
    path: 'architecture/integration',
    icon: 'extension',
    description: 'Kết nối alias, configuration, routes và menu theo cùng một hợp đồng.',
    order: 6,
  },
  {
    id: 'di',
    group: 'Angular hiện đại',
    title: 'Dependency Injection',
    path: 'modern-angular/dependency-injection',
    icon: 'hub',
    description: 'Chọn phạm vi provider và quan sát instance thực tế.',
    order: 7,
  },
  {
    id: 'signals',
    group: 'Angular hiện đại',
    title: 'Signals & Component APIs',
    path: 'modern-angular/signals',
    icon: 'bolt',
    description: 'Dữ liệu đi xuống, sự kiện đi lên; computed giữ giá trị dẫn xuất nhất quán.',
    order: 8,
  },
  {
    id: 'permission-model',
    group: 'Phân quyền',
    title: 'Permission, Group & Role',
    path: 'authorization/model',
    icon: 'shield',
    description: 'Role nhận nhóm nghiệp vụ G; hệ thống suy ra các quyền C và A.',
    order: 9,
  },
  {
    id: 'permission-checks',
    group: 'Phân quyền',
    title: 'Menu, Route & Action',
    path: 'authorization/checks',
    icon: 'verified_user',
    description: 'Kiểm tra giao diện, đường dẫn trực tiếp và API ở đúng lớp.',
    order: 10,
  },
  {
    id: 'data-scope',
    group: 'Phân quyền',
    title: 'Quyền dữ liệu & Assignment Context',
    path: 'authorization/data-scope',
    icon: 'manage_accounts',
    description: 'Kết hợp quyền hành động với quan hệ người dùng và bản ghi.',
    order: 11,
  },
  {
    id: 'typescript',
    group: 'Coding Conventions',
    title: 'TypeScript & Naming',
    path: 'coding-convention/typescript',
    icon: 'code',
    description: 'Tên thể hiện ý định, kiểu dữ liệu rõ ràng và xử lý lỗi đầy đủ.',
    order: 12,
  },
  {
    id: 'spacing',
    group: 'Coding Conventions',
    title: 'CSS/SCSS & UI Spacing',
    path: 'coding-convention/scss',
    icon: 'space_dashboard',
    description: 'Form p-20 gap-8; màn xem gap-16 để đọc dữ liệu gọn gàng.',
    order: 13,
  },
  {
    id: 'quality',
    group: 'Coding Conventions',
    title: 'Chất lượng code & Accessibility',
    path: 'coding-convention/quality',
    icon: 'accessibility_new',
    description: 'Ngữ nghĩa HTML, bàn phím và thông báo trạng thái là một phần của UI.',
    order: 14,
  },
  {
    id: 'git',
    group: 'Công cụ & cấu hình',
    title: 'Git & Submodules',
    path: 'tooling/git-submodules',
    icon: 'fork_right',
    description: 'Phân biệt commit của Portal, gitlink và working tree của submodule.',
    order: 15,
  },
  {
    id: 'theme',
    group: 'Công cụ & cấu hình',
    title: 'Theme & Design Tokens',
    path: 'custom-theme/guide',
    icon: 'palette',
    description: 'Từ màu thương hiệu đến palette, trạng thái và độ tương phản.',
    order: 16,
  },
  {
    id: 'portal-config',
    group: 'Công cụ & cấu hình',
    title: 'Cấu hình Portal',
    path: 'portal-config',
    icon: 'tune',
    description: 'Thử ba phiên bản sidebar và lưu cấu hình toàn cục.',
    order: 17,
  },
] as const;
export type InstructionId = (typeof INSTRUCTIONS)[number]['id'];
export const INSTRUCTION_GROUPS = [...new Set(INSTRUCTIONS.map(article => article.group))];
