import type { PagePattern } from './pattern.model';
/** Serializable page selection guide and record URL contract. */
export const PAGE_PATTERNS: PagePattern[] = [
  {
    id: 'roles-matrix',
    name: 'Role / Ma trận quyền',
    route: '/pages/list/roles-matrix',
    recordRoutes: {
      create: '/pages/list/roles-matrix/create',
      detail: '/pages/list/roles-matrix/:id/detail',
      update: '/pages/list/roles-matrix/:id/update',
    },
    coreVersion: '22.2.8',
    entityKind: 'role',
    entityLabel: 'Vai trò',
    purpose: 'Quản lý vai trò và gán quyền nhóm theo module bằng ma trận CRUD và Other.',
    dataShape: 'permission-matrix',
    density: 'compact',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: ['module → entity → permission group'],
    interactions: [
      'code-link',
      'search',
      'filter',
      'paginate',
      'create',
      'detail',
      'update',
      'module-tabs',
      'scoped-selection',
      'indeterminate',
      'session-storage',
      'unsaved-guard',
    ],
    suitableWhen: 'So sánh nhanh CRUD theo chức năng; các hành động bổ sung nằm trong Other.',
    avoidWhen: 'Cần cấp quyền người dùng thực hoặc thực thi phân quyền backend.',
    components: [
      'SdPageComponent',
      'SdTable',
      'SdTableCellDefDirective',
      'SdSection',
      'SdTabGroup',
      'SdTab',
      'SdInput',
      'SdSelect',
      'MatCheckbox',
    ],
    sourceFiles: [
      'src/modules/pages/features/roles/pages/role-list-page.component.ts',
      'src/modules/pages/features/roles/pages/role-record-editor.component.ts',
      'src/modules/pages/features/roles/components/role-permission-editor.component.ts',
      'src/modules/pages/features/roles/components/permission-matrix.component.ts',
      'src/modules/pages/features/roles/data/role-session.store.ts',
    ],
    dataContract: 'src/modules/pages/features/roles/data/role.model.ts',
    fixtures: 'src/modules/pages/features/roles/data/role.fixtures.ts',
    responsive: 'List chiếm chiều cao vùng làm việc; form thu về một cột, bảng quyền cuộn ngang và giữ cột chức năng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error', 'saving', 'invalid', 'unsaved'],
  },
  {
    id: 'roles-tree',
    name: 'Role / Quyền phân cấp',
    route: '/pages/list/roles-tree',
    recordRoutes: {
      create: '/pages/list/roles-tree/create',
      detail: '/pages/list/roles-tree/:id/detail',
      update: '/pages/list/roles-tree/:id/update',
    },
    coreVersion: '22.2.8',
    entityKind: 'role',
    entityLabel: 'Vai trò',
    purpose: 'Quản lý vai trò và gán quyền nhóm theo module bằng bảng cha–con.',
    dataShape: 'permission-tree',
    density: 'compact',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: ['module → entity → permission group'],
    interactions: [
      'code-link',
      'search',
      'filter',
      'paginate',
      'create',
      'detail',
      'update',
      'module-tabs',
      'scoped-selection',
      'indeterminate',
      'session-storage',
      'unsaved-guard',
    ],
    suitableWhen: 'Duyệt nhiều quyền với tên dài; cần thu gọn hoặc mở rộng từng chức năng.',
    avoidWhen: 'Cần cấp quyền người dùng thực hoặc thực thi phân quyền backend.',
    components: [
      'SdPageComponent',
      'SdTable',
      'SdTableCellDefDirective',
      'SdSection',
      'SdTabGroup',
      'SdTab',
      'SdInput',
      'SdSelect',
      'MatCheckbox',
    ],
    sourceFiles: [
      'src/modules/pages/features/roles/pages/role-list-page.component.ts',
      'src/modules/pages/features/roles/pages/role-record-editor.component.ts',
      'src/modules/pages/features/roles/components/role-permission-editor.component.ts',
      'src/modules/pages/features/roles/components/permission-tree.component.ts',
      'src/modules/pages/features/roles/data/role-session.store.ts',
    ],
    dataContract: 'src/modules/pages/features/roles/data/role.model.ts',
    fixtures: 'src/modules/pages/features/roles/data/role.fixtures.ts',
    responsive: 'List chiếm chiều cao vùng làm việc; form thu về một cột, bảng quyền cuộn ngang và giữ cột chức năng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error', 'saving', 'invalid', 'unsaved'],
  },
  {
    id: 'list-standard',
    name: 'List / Standard',
    route: '/pages/list/list-standard',
    coreVersion: '22.2.8',
    entityKind: 'customer',
    entityLabel: 'Khách hàng doanh nghiệp',
    purpose: 'Tra cứu khách hàng bằng quickSearch, từ khóa và trạng thái trên một hàng gọn.',
    dataShape: 'flat',
    density: 'comfortable-table',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: [
      'code-link',
      'badge-tag',
      'search',
      'filter',
      'sort',
      'paginate',
      'detail',
      'create',
      'update',
      'quickSearch',
      'quickSearch.filters',
      'deep-link',
      'history-navigation',
      'guarded-back',
    ],
    suitableWhen: 'Tra cứu khách hàng bằng quickSearch, từ khóa và trạng thái trên một hàng gọn.',
    avoidWhen: 'Dữ liệu phân cấp sâu; nhiều thao tác phụ thuộc quan hệ.',
    components: ['SdTableCellDefDirective', 'SdBadge', 'SdPageComponent', 'SdTable'],
    sourceFiles: [
      'src/modules/pages/components/status-badge.ts',
      'src/modules/pages/features/list-standard/list-standard.component.ts',
      'src/modules/pages/features/list-standard/list-standard.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Chiếm 100% chiều cao vùng làm việc; bảng cuộn nội bộ, phân trang ở đáy khi đủ số dòng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/list/list-standard/create',
      detail: '/pages/list/list-standard/:id/detail',
      update: '/pages/list/list-standard/:id/update',
    },
  },
  {
    id: 'list-advanced-filter',
    name: 'List / Advanced filter',
    route: '/pages/list/list-advanced-filter',
    coreVersion: '22.2.8',
    entityKind: 'order',
    entityLabel: 'Đơn hàng',
    purpose: 'Quản lý đơn hàng với quickSearch, externalFilters và score card theo dữ liệu phiên.',
    dataShape: 'filterable',
    density: 'comfortable-table',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: [
      'code-link',
      'badge-round',
      'search',
      'filter',
      'sort',
      'paginate',
      'detail',
      'create',
      'update',
      'quickSearch',
      'externalFilters',
      'score-cards',
      'deep-link',
      'history-navigation',
      'guarded-back',
    ],
    suitableWhen: 'Quản lý đơn hàng với quickSearch, externalFilters và score card theo dữ liệu phiên.',
    avoidWhen: 'Danh sách rất ngắn chỉ cần tìm nhanh.',
    components: ['SdTableCellDefDirective', 'SdBadge', 'SdPageComponent', 'SdTable'],
    sourceFiles: [
      'src/modules/pages/components/status-badge.ts',
      'src/modules/pages/data/table-query.ts',
      'src/modules/pages/features/list-advanced-filter/list-advanced-filter.component.ts',
      'src/modules/pages/features/list-advanced-filter/list-advanced-filter.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Chiếm 100% chiều cao vùng làm việc; bảng cuộn nội bộ, phân trang ở đáy khi đủ số dòng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/list/list-advanced-filter/create',
      detail: '/pages/list/list-advanced-filter/:id/detail',
      update: '/pages/list/list-advanced-filter/:id/update',
    },
  },
  {
    id: 'list-grouped-tree',
    name: 'List / Grouped tree',
    route: '/pages/list/list-grouped-tree',
    coreVersion: '22.2.8',
    entityKind: 'product',
    entityLabel: 'Nhóm hàng và sản phẩm',
    purpose: 'Tra cứu danh mục phân cấp với externalFilters của Core.',
    dataShape: 'hierarchical',
    density: 'comfortable-table',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: ['parentId'],
    interactions: [
      'code-link',
      'badge-icon',
      'search',
      'filter',
      'sort',
      'paginate',
      'detail',
      'create',
      'update',
      'externalFilters',
      'deep-link',
      'history-navigation',
      'guarded-back',
    ],
    suitableWhen: 'Tra cứu danh mục phân cấp với externalFilters của Core.',
    avoidWhen: 'Mạng quan hệ nhiều-nhiều hoặc dữ liệu không có cha/con.',
    components: ['SdTableCellDefDirective', 'SdBadge', 'SdPageComponent', 'SdTable'],
    sourceFiles: [
      'src/modules/pages/components/status-badge.ts',
      'src/modules/pages/data/table-query.ts',
      'src/modules/pages/features/list-grouped-tree/list-grouped-tree.component.ts',
      'src/modules/pages/features/list-grouped-tree/list-grouped-tree.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Chiếm 100% chiều cao vùng làm việc; bảng cuộn nội bộ, phân trang ở đáy khi đủ số dòng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/list/list-grouped-tree/create',
      detail: '/pages/list/list-grouped-tree/:id/detail',
      update: '/pages/list/list-grouped-tree/:id/update',
    },
  },
  {
    id: 'list-master-detail',
    name: 'List / Master–Detail',
    route: '/pages/list/list-master-detail',
    coreVersion: '22.2.8',
    entityKind: 'ticket',
    entityLabel: 'Yêu cầu hỗ trợ',
    purpose: 'Xử lý yêu cầu với quickSearch, score card và vùng chi tiết độc lập bên cạnh.',
    dataShape: 'sequential',
    density: 'comfortable-table',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: [
      'code-link',
      'badge-icon',
      'search',
      'filter',
      'sort',
      'paginate',
      'detail',
      'create',
      'update',
      'quickSearch',
      'quickSearch.filters',
      'score-cards',
      'deep-link',
      'history-navigation',
      'guarded-back',
    ],
    suitableWhen: 'Xử lý yêu cầu với quickSearch, score card và vùng chi tiết độc lập bên cạnh.',
    avoidWhen: 'Biểu mẫu dài cần không gian làm việc riêng.',
    components: ['SdTableCellDefDirective', 'SdBadge', 'SdPageComponent', 'SdTable'],
    sourceFiles: [
      'src/modules/pages/components/status-badge.ts',
      'src/modules/pages/features/list-master-detail/list-master-detail.component.ts',
      'src/modules/pages/features/list-master-detail/list-master-detail.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Chiếm 100% chiều cao vùng làm việc; bảng cuộn nội bộ, phân trang ở đáy khi đủ số dòng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/list/list-master-detail/create',
      detail: '/pages/list/list-master-detail/:id/detail',
      update: '/pages/list/list-master-detail/:id/update',
    },
  },
  {
    id: 'detail-overview',
    name: 'Detail / Overview',
    route: '/pages/detail/detail-overview',
    coreVersion: '22.2.8',
    entityKind: 'customer',
    entityLabel: 'Khách hàng',
    purpose: 'Xem thông tin chính và một vài nhóm thuộc tính.',
    dataShape: 'flat',
    density: 'comfortable-form',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: ['read', 'update', 'deep-link', 'history-navigation', 'guarded-back'],
    suitableWhen: 'Xem thông tin chính và một vài nhóm thuộc tính.',
    avoidWhen: 'Có nhiều bảng liên quan cần tách tab.',
    components: ['SdPageComponent', 'SdView', 'SdSection'],
    sourceFiles: [
      'src/modules/pages/features/detail-overview/detail-overview.component.ts',
      'src/modules/pages/features/detail-overview/detail-overview.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/detail-overview/create',
      detail: '/pages/detail/detail-overview/:id/detail',
      update: '/pages/detail/detail-overview/:id/update',
    },
  },
  {
    id: 'detail-tabbed',
    name: 'Detail / Tabbed',
    route: '/pages/detail/detail-tabbed',
    coreVersion: '22.2.8',
    entityKind: 'contract',
    entityLabel: 'Hợp đồng',
    purpose: 'Tách nhóm nội dung và dữ liệu liên quan theo tác vụ đọc.',
    dataShape: 'relational',
    density: 'comfortable-form',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: ['lines'],
    interactions: ['read', 'update', 'deep-link', 'history-navigation', 'guarded-back'],
    suitableWhen: 'Tách nhóm nội dung và dữ liệu liên quan theo tác vụ đọc.',
    avoidWhen: 'Người dùng cần đối chiếu mọi trường cùng lúc.',
    components: ['SdPageComponent', 'SdView', 'SdSection'],
    sourceFiles: [
      'src/modules/pages/features/detail-tabbed/detail-tabbed.component.ts',
      'src/modules/pages/features/detail-tabbed/detail-tabbed.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/detail-tabbed/create',
      detail: '/pages/detail/detail-tabbed/:id/detail',
      update: '/pages/detail/detail-tabbed/:id/update',
    },
  },
  {
    id: 'detail-related-records',
    name: 'Detail / Related records',
    route: '/pages/detail/detail-related-records',
    coreVersion: '22.2.8',
    entityKind: 'order',
    entityLabel: 'Đơn hàng',
    purpose: 'Đọc bản ghi chính cùng các dòng hàng để đối chiếu.',
    dataShape: 'parent-lines',
    density: 'comfortable-form',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: ['lines'],
    interactions: ['read', 'update', 'deep-link', 'history-navigation', 'guarded-back'],
    suitableWhen: 'Đọc bản ghi chính cùng các dòng hàng để đối chiếu.',
    avoidWhen: 'Child records có nghiệp vụ hoàn toàn độc lập.',
    components: ['SdPageComponent', 'SdView', 'SdSection'],
    sourceFiles: [
      'src/modules/pages/features/detail-related-records/detail-related-records.component.ts',
      'src/modules/pages/features/detail-related-records/detail-related-records.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/detail-related-records/create',
      detail: '/pages/detail/detail-related-records/:id/detail',
      update: '/pages/detail/detail-related-records/:id/update',
    },
  },
  {
    id: 'form-simple',
    name: 'Form / Simple',
    route: '/pages/detail/form-simple',
    coreVersion: '22.2.8',
    entityKind: 'category',
    entityLabel: 'Danh mục',
    purpose: 'Nhập nhanh một nhóm trường có cùng ý nghĩa.',
    dataShape: 'flat',
    density: 'comfortable-form',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: ['create', 'update', 'validation', 'dirty-close', 'deep-link', 'history-navigation', 'guarded-back'],
    suitableWhen: 'Nhập nhanh một nhóm trường có cùng ý nghĩa.',
    avoidWhen: 'Thông tin có nhiều nhóm hoặc dòng con.',
    components: ['SdPageComponent', 'SdInput', 'SdSelect', 'SdSection'],
    sourceFiles: [
      'src/modules/pages/features/form-simple/form-simple.component.ts',
      'src/modules/pages/features/form-simple/form-simple.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/form-simple/create',
      detail: '/pages/detail/form-simple/:id/detail',
      update: '/pages/detail/form-simple/:id/update',
    },
  },
  {
    id: 'form-sections',
    name: 'Form / Sections',
    route: '/pages/detail/form-sections',
    coreVersion: '22.2.8',
    entityKind: 'partner',
    entityLabel: 'Đối tác',
    purpose: 'Chia nhóm trường theo nội dung và thứ tự làm việc.',
    dataShape: 'sectioned',
    density: 'comfortable-form',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: ['create', 'update', 'validation', 'dirty-close', 'deep-link', 'history-navigation', 'guarded-back'],
    suitableWhen: 'Chia nhóm trường theo nội dung và thứ tự làm việc.',
    avoidWhen: 'Thao tác chỉ có một hoặc hai trường đơn giản.',
    components: ['SdPageComponent', 'SdInput', 'SdSelect', 'SdSection'],
    sourceFiles: [
      'src/modules/pages/features/form-sections/form-sections.component.ts',
      'src/modules/pages/features/form-sections/form-sections.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/form-sections/create',
      detail: '/pages/detail/form-sections/:id/detail',
      update: '/pages/detail/form-sections/:id/update',
    },
  },
  {
    id: 'form-line-items',
    name: 'Form / Line items',
    route: '/pages/detail/form-line-items',
    coreVersion: '22.2.8',
    entityKind: 'order',
    entityLabel: 'Đơn hàng',
    purpose: 'Lưu header và các dòng con trong một giao dịch.',
    dataShape: 'parent-lines',
    density: 'comfortable-form',
    container: 'page',
    requiredFields: ['code', 'name', 'status'],
    relationships: ['lines'],
    interactions: ['create', 'update', 'validation', 'dirty-close', 'deep-link', 'history-navigation', 'guarded-back'],
    suitableWhen: 'Lưu header và các dòng con trong một giao dịch.',
    avoidWhen: 'Dòng con có vòng đời hoặc API lưu độc lập.',
    components: ['SdPageComponent', 'SdInput', 'SdSelect', 'SdSection'],
    sourceFiles: [
      'src/modules/pages/features/form-line-items/form-line-items.component.ts',
      'src/modules/pages/features/form-line-items/form-line-items.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/form-line-items/create',
      detail: '/pages/detail/form-line-items/:id/detail',
      update: '/pages/detail/form-line-items/:id/update',
    },
  },
  {
    id: 'drawer-compact',
    name: 'Drawer / Compact',
    route: '/pages/detail/drawer-compact',
    coreVersion: '22.2.8',
    entityKind: 'category',
    entityLabel: 'Danh mục',
    purpose: 'Xem và sửa ngắn tại danh sách, giữ ngữ cảnh phía sau.',
    dataShape: 'flat',
    density: 'comfortable-form',
    container: 'side-drawer',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: [
      'code-link',
      'badge-round',
      'detail',
      'create',
      'update',
      'dirty-close',
      'deep-link',
      'history-navigation',
      'guarded-back',
    ],
    suitableWhen: 'Xem và sửa ngắn tại danh sách, giữ ngữ cảnh phía sau.',
    avoidWhen: 'Chỉnh sửa dài hoặc cần URL làm việc riêng.',
    components: ['SdTableCellDefDirective', 'SdBadge', 'SdPageComponent', 'SdInput', 'SdSelect', 'SdSection', 'SdSideDrawer'],
    sourceFiles: [
      'src/modules/pages/components/status-badge.ts',
      'src/modules/pages/features/drawer-compact/drawer-compact.component.ts',
      'src/modules/pages/features/drawer-compact/drawer-compact.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
      'src/modules/pages/features/drawer-pattern-base.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/drawer-compact/create',
      detail: '/pages/detail/drawer-compact/:id/detail',
      update: '/pages/detail/drawer-compact/:id/update',
    },
  },
  {
    id: 'drawer-sections',
    name: 'Drawer / Sections',
    route: '/pages/detail/drawer-sections',
    coreVersion: '22.2.8',
    entityKind: 'contact',
    entityLabel: 'Liên hệ',
    purpose: 'Chỉnh sửa vài nhóm thông tin trong ngữ cảnh danh sách.',
    dataShape: 'sectioned',
    density: 'comfortable-form',
    container: 'side-drawer',
    requiredFields: ['code', 'name', 'status'],
    relationships: [],
    interactions: [
      'code-link',
      'badge-tag',
      'detail',
      'create',
      'update',
      'dirty-close',
      'deep-link',
      'history-navigation',
      'guarded-back',
    ],
    suitableWhen: 'Chỉnh sửa vài nhóm thông tin trong ngữ cảnh danh sách.',
    avoidWhen: 'Nhiều quan hệ hoặc bảng lồng nhau làm drawer quá dài.',
    components: ['SdTableCellDefDirective', 'SdBadge', 'SdPageComponent', 'SdInput', 'SdSelect', 'SdSection', 'SdSideDrawer'],
    sourceFiles: [
      'src/modules/pages/components/status-badge.ts',
      'src/modules/pages/features/drawer-sections/drawer-sections.component.ts',
      'src/modules/pages/features/drawer-sections/drawer-sections.component.html',
      'src/modules/pages/reference/page-navigation.ts',
      'src/modules/pages/components/record-header.component.ts',
      'src/modules/pages/features/drawer-pattern-base.ts',
    ],
    dataContract: 'src/modules/pages/data/models.ts',
    fixtures: 'src/modules/pages/data/fixture-factories.ts',
    responsive: 'Hai cột chuyển một cột dưới 900px; bảng cuộn trong vùng riêng.',
    states: ['data', 'loading', 'empty', 'no-results', 'error'],
    recordRoutes: {
      create: '/pages/detail/drawer-sections/create',
      detail: '/pages/detail/drawer-sections/:id/detail',
      update: '/pages/detail/drawer-sections/:id/update',
    },
  },
];
