/** Source inventory for the three documented demo groups; compared with Storybook's live index. */
export const DEMO_INVENTORY = [
  {
    title: 'Components/anchor',
    componentSource: 'src/libs/components/anchor/basic/basic.component.ts',
    storyFile: 'src/libs/components/anchor/anchor.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/anchor/basic',
    componentSource: 'src/libs/components/anchor/basic/basic.component.ts',
    storyFile: 'src/libs/components/anchor/basic/basic.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/anchor/with-section',
    componentSource: 'src/libs/components/anchor/with-section/with-section.component.ts',
    storyFile: 'src/libs/components/anchor/with-section/with-section.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/avatar',
    componentSource: 'src/libs/components/avatar/avatar.component.ts',
    storyFile: 'src/libs/components/avatar/avatar.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/badge',
    componentSource: 'src/libs/components/badge/badge.component.ts',
    storyFile: 'src/libs/components/badge/badge.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/button',
    componentSource: 'src/libs/components/button/button.component.ts',
    storyFile: 'src/libs/components/button/button.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/modal/basic',
    componentSource: 'src/libs/components/modal/basic/basic.component.ts',
    storyFile: 'src/libs/components/modal/basic/basic.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/modal/slots',
    componentSource: 'src/libs/components/modal/slots/slots.component.ts',
    storyFile: 'src/libs/components/modal/slots/slots.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/modal/view-modes',
    componentSource: 'src/libs/components/modal/view-modes/view-modes.component.ts',
    storyFile: 'src/libs/components/modal/view-modes/view-modes.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/preview-image',
    componentSource: 'src/libs/components/preview-image/preview-image.component.ts',
    storyFile: 'src/libs/components/preview-image/preview-image.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/preview-pdf',
    componentSource: 'src/libs/components/preview-pdf/preview-pdf.component.ts',
    storyFile: 'src/libs/components/preview-pdf/preview-pdf.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/query-bar/basic',
    componentSource: 'src/libs/components/query-bar/basic/basic.component.ts',
    storyFile: 'src/libs/components/query-bar/basic/basic.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/query-bar/fields',
    componentSource: 'src/libs/components/query-bar/fields/fields.component.ts',
    storyFile: 'src/libs/components/query-bar/fields/fields.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/query-bar/modes',
    componentSource: 'src/libs/components/query-bar/modes/modes.component.ts',
    storyFile: 'src/libs/components/query-bar/modes/modes.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/section/basic',
    componentSource: 'src/libs/components/section/basic/basic.component.ts',
    storyFile: 'src/libs/components/section/basic/basic.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/section/header-slots',
    componentSource: 'src/libs/components/section/header-slots/header-slots.component.ts',
    storyFile: 'src/libs/components/section/header-slots/header-slots.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/section/section-item',
    componentSource: 'src/libs/components/section/section-item/section-item.component.ts',
    storyFile: 'src/libs/components/section/section-item/section-item.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/side-drawer/advanced',
    componentSource: 'src/libs/components/side-drawer/advanced/advanced.component.ts',
    storyFile: 'src/libs/components/side-drawer/advanced/advanced.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/side-drawer/basic',
    componentSource: 'src/libs/components/side-drawer/basic/basic.component.ts',
    storyFile: 'src/libs/components/side-drawer/basic/basic.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/side-drawer/custom',
    componentSource: 'src/libs/components/side-drawer/custom/custom.component.ts',
    storyFile: 'src/libs/components/side-drawer/custom/custom.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/side-drawer/loading',
    componentSource: 'src/libs/components/side-drawer/loading/loading.component.ts',
    storyFile: 'src/libs/components/side-drawer/loading/loading.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/splitter',
    componentSource: 'src/libs/components/splitter/splitter.component.ts',
    storyFile: 'src/libs/components/splitter/splitter.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/table/basic',
    componentSource: 'src/libs/components/table/basic/basic.component.ts',
    storyFile: 'src/libs/components/table/basic/basic.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/table/column',
    componentSource: 'src/libs/components/table/column/column.component.ts',
    storyFile: 'src/libs/components/table/column/column.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/table/filter',
    componentSource: 'src/libs/components/table/filter/filter.component.ts',
    storyFile: 'src/libs/components/table/filter/filter.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/table/index-column',
    componentSource: 'src/libs/components/table/index-column/index-column.component.ts',
    storyFile: 'src/libs/components/table/index-column/index-column.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/table/tree',
    componentSource: 'src/libs/components/table/tree/tree.component.ts',
    storyFile: 'src/libs/components/table/tree/tree.stories.ts',
    status: 'covered',
  },
  {
    title: 'Components/upload-file',
    componentSource: 'src/libs/components/upload-file/upload-file.component.ts',
    storyFile: 'src/libs/components/upload-file/upload-file.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/checkbox',
    componentSource: 'src/libs/forms/checkbox/checkbox.component.ts',
    storyFile: 'src/libs/forms/checkbox/checkbox.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/chip-calendar',
    componentSource: 'src/libs/forms/chip-calendar/chip-calendar.component.ts',
    storyFile: 'src/libs/forms/chip-calendar/chip-calendar.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/chip',
    componentSource: 'src/libs/forms/chip/chip.component.ts',
    storyFile: 'src/libs/forms/chip/chip.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/date',
    componentSource: 'src/libs/forms/date/date.component.ts',
    storyFile: 'src/libs/forms/date/date.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/datetime',
    componentSource: 'src/libs/forms/datetime/datetime.component.ts',
    storyFile: 'src/libs/forms/datetime/datetime.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/input-number',
    componentSource: 'src/libs/forms/input-number/input-number.component.ts',
    storyFile: 'src/libs/forms/input-number/input-number.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/input',
    componentSource: 'src/libs/forms/input/input.component.ts',
    storyFile: 'src/libs/forms/input/input.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/radio',
    componentSource: 'src/libs/forms/radio/radio.component.ts',
    storyFile: 'src/libs/forms/radio/radio.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/select',
    componentSource: 'src/libs/forms/select/select.component.ts',
    storyFile: 'src/libs/forms/select/select.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/switch',
    componentSource: 'src/libs/forms/switch/switch.component.ts',
    storyFile: 'src/libs/forms/switch/switch.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/textarea',
    componentSource: 'src/libs/forms/textarea/textarea.component.ts',
    storyFile: 'src/libs/forms/textarea/textarea.stories.ts',
    status: 'covered',
  },
  {
    title: 'Forms/validation',
    componentSource: 'src/libs/forms/validation/validation.component.ts',
    storyFile: 'src/libs/forms/validation/validation.stories.ts',
    status: 'covered',
  },
  {
    title: 'Services/confirm/confirm',
    componentSource: 'src/libs/services/confirm/confirm/confirm.component.ts',
    storyFile: 'src/libs/services/confirm/confirm/confirm.stories.ts',
    status: 'covered',
  },
  {
    title: 'Services/confirm/with-date',
    componentSource: 'src/libs/services/confirm/with-date/with-date.component.ts',
    storyFile: 'src/libs/services/confirm/with-date/with-date.stories.ts',
    status: 'covered',
  },
  {
    title: 'Services/confirm/with-input',
    componentSource: 'src/libs/services/confirm/with-input/with-input.component.ts',
    storyFile: 'src/libs/services/confirm/with-input/with-input.stories.ts',
    status: 'covered',
  },
  {
    title: 'Services/confirm/with-radio',
    componentSource: 'src/libs/services/confirm/with-radio/with-radio.component.ts',
    storyFile: 'src/libs/services/confirm/with-radio/with-radio.stories.ts',
    status: 'covered',
  },
  {
    title: 'Services/loading',
    componentSource: 'src/libs/services/loading/loading.component.ts',
    storyFile: 'src/libs/services/loading/loading.stories.ts',
    status: 'covered',
  },
  {
    title: 'Services/notify',
    componentSource: 'src/libs/services/notify/notify.component.ts',
    storyFile: 'src/libs/services/notify/notify.stories.ts',
    status: 'covered',
  },
  {
    title: 'Services/Unsaved changes',
    componentSource: 'src/libs/services/unsaved-changes/unsaved-changes.component.ts',
    storyFile: 'src/libs/services/unsaved-changes/unsaved-changes.stories.ts',
    status: 'covered',
  },
] as const;
export const STORYBOOK_GROUP_ORDER = ['Components', 'Forms', 'Services', 'Pages'];
